// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stallstjarnornas.WebAPI.Data;

#nullable disable

namespace Stallstjarnornas.WebAPI.Migrations
{
    [DbContext(typeof(StallstjarnornasDbContext))]
    [Migration("20260512112720_AddedTable")]
    partial class AddedTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Stallstjarnornas.Library.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BookingNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuestId")
                        .HasColumnType("int");

                    b.Property<int>("NoOfGuests")
                        .HasColumnType("int");

                    b.Property<int>("SittingId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GuestId");

                    b.HasIndex("SittingId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookingDate = new DateTime(2026, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingNumber = 1001,
                            CreatedDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 1,
                            NoOfGuests = 2,
                            SittingId = 1,
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 2,
                            BookingDate = new DateTime(2026, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingNumber = 1002,
                            CreatedDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 2,
                            NoOfGuests = 4,
                            SittingId = 2,
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 3,
                            BookingDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingNumber = 1003,
                            CreatedDate = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 3,
                            NoOfGuests = 3,
                            SittingId = 3,
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 4,
                            BookingDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingNumber = 1004,
                            CreatedDate = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 4,
                            NoOfGuests = 6,
                            SittingId = 4,
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 5,
                            BookingDate = new DateTime(2026, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingNumber = 1005,
                            CreatedDate = new DateTime(2026, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 5,
                            NoOfGuests = 2,
                            SittingId = 5,
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 6,
                            BookingDate = new DateTime(2026, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingNumber = 1006,
                            CreatedDate = new DateTime(2026, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 6,
                            NoOfGuests = 5,
                            SittingId = 6,
                            Status = "Cancelled"
                        },
                        new
                        {
                            Id = 7,
                            BookingDate = new DateTime(2026, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingNumber = 1007,
                            CreatedDate = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 7,
                            NoOfGuests = 8,
                            SittingId = 7,
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 8,
                            BookingDate = new DateTime(2026, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingNumber = 1008,
                            CreatedDate = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 8,
                            NoOfGuests = 2,
                            SittingId = 8,
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 9,
                            BookingDate = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingNumber = 1009,
                            CreatedDate = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 9,
                            NoOfGuests = 4,
                            SittingId = 9,
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 10,
                            BookingDate = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingNumber = 1010,
                            CreatedDate = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 10,
                            NoOfGuests = 3,
                            SittingId = 10,
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 11,
                            BookingDate = new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingNumber = 1011,
                            CreatedDate = new DateTime(2026, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 11,
                            NoOfGuests = 7,
                            SittingId = 11,
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 12,
                            BookingDate = new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingNumber = 1012,
                            CreatedDate = new DateTime(2026, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 12,
                            NoOfGuests = 2,
                            SittingId = 12,
                            Status = "Cancelled"
                        },
                        new
                        {
                            Id = 13,
                            BookingDate = new DateTime(2026, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingNumber = 1013,
                            CreatedDate = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 13,
                            NoOfGuests = 5,
                            SittingId = 1,
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 14,
                            BookingDate = new DateTime(2026, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingNumber = 1014,
                            CreatedDate = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 14,
                            NoOfGuests = 2,
                            SittingId = 2,
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 15,
                            BookingDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingNumber = 1015,
                            CreatedDate = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 15,
                            NoOfGuests = 4,
                            SittingId = 3,
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 16,
                            BookingDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingNumber = 1016,
                            CreatedDate = new DateTime(2026, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 16,
                            NoOfGuests = 3,
                            SittingId = 4,
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 17,
                            BookingDate = new DateTime(2026, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingNumber = 1017,
                            CreatedDate = new DateTime(2026, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 17,
                            NoOfGuests = 6,
                            SittingId = 5,
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 18,
                            BookingDate = new DateTime(2026, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingNumber = 1018,
                            CreatedDate = new DateTime(2026, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 18,
                            NoOfGuests = 2,
                            SittingId = 6,
                            Status = "Cancelled"
                        },
                        new
                        {
                            Id = 19,
                            BookingDate = new DateTime(2026, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingNumber = 1019,
                            CreatedDate = new DateTime(2026, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 19,
                            NoOfGuests = 4,
                            SittingId = 7,
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 20,
                            BookingDate = new DateTime(2026, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingNumber = 1020,
                            CreatedDate = new DateTime(2026, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 20,
                            NoOfGuests = 10,
                            SittingId = 8,
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 21,
                            BookingDate = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingNumber = 1021,
                            CreatedDate = new DateTime(2026, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 21,
                            NoOfGuests = 2,
                            SittingId = 9,
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 22,
                            BookingDate = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingNumber = 1022,
                            CreatedDate = new DateTime(2026, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 22,
                            NoOfGuests = 3,
                            SittingId = 10,
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 23,
                            BookingDate = new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingNumber = 1023,
                            CreatedDate = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 23,
                            NoOfGuests = 5,
                            SittingId = 11,
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 24,
                            BookingDate = new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingNumber = 1024,
                            CreatedDate = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 24,
                            NoOfGuests = 4,
                            SittingId = 12,
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 25,
                            BookingDate = new DateTime(2026, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingNumber = 1025,
                            CreatedDate = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 25,
                            NoOfGuests = 2,
                            SittingId = 1,
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 26,
                            BookingDate = new DateTime(2026, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingNumber = 1026,
                            CreatedDate = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 26,
                            NoOfGuests = 6,
                            SittingId = 2,
                            Status = "Cancelled"
                        },
                        new
                        {
                            Id = 27,
                            BookingDate = new DateTime(2026, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingNumber = 1027,
                            CreatedDate = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 27,
                            NoOfGuests = 3,
                            SittingId = 5,
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 28,
                            BookingDate = new DateTime(2026, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingNumber = 1028,
                            CreatedDate = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 28,
                            NoOfGuests = 2,
                            SittingId = 6,
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 29,
                            BookingDate = new DateTime(2026, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingNumber = 1029,
                            CreatedDate = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 29,
                            NoOfGuests = 4,
                            SittingId = 7,
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 30,
                            BookingDate = new DateTime(2026, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingNumber = 1030,
                            CreatedDate = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 30,
                            NoOfGuests = 5,
                            SittingId = 8,
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 31,
                            BookingDate = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingNumber = 1031,
                            CreatedDate = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 1,
                            NoOfGuests = 2,
                            SittingId = 9,
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 32,
                            BookingDate = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingNumber = 1032,
                            CreatedDate = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 3,
                            NoOfGuests = 3,
                            SittingId = 10,
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 33,
                            BookingDate = new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingNumber = 1033,
                            CreatedDate = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 5,
                            NoOfGuests = 4,
                            SittingId = 11,
                            Status = "Cancelled"
                        },
                        new
                        {
                            Id = 34,
                            BookingDate = new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingNumber = 1034,
                            CreatedDate = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 7,
                            NoOfGuests = 2,
                            SittingId = 12,
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 35,
                            BookingDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingNumber = 1035,
                            CreatedDate = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 9,
                            NoOfGuests = 6,
                            SittingId = 3,
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 36,
                            BookingDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingNumber = 1036,
                            CreatedDate = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 11,
                            NoOfGuests = 3,
                            SittingId = 4,
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 37,
                            BookingDate = new DateTime(2026, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingNumber = 1037,
                            CreatedDate = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 13,
                            NoOfGuests = 2,
                            SittingId = 7,
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 38,
                            BookingDate = new DateTime(2026, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingNumber = 1038,
                            CreatedDate = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 15,
                            NoOfGuests = 5,
                            SittingId = 8,
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 39,
                            BookingDate = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingNumber = 1039,
                            CreatedDate = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 17,
                            NoOfGuests = 4,
                            SittingId = 9,
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 40,
                            BookingDate = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingNumber = 1040,
                            CreatedDate = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 19,
                            NoOfGuests = 3,
                            SittingId = 10,
                            Status = "Cancelled"
                        });
                });

            modelBuilder.Entity("Stallstjarnornas.Library.Models.Guest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Guests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "anna.lindqvist@gmail.com",
                            Name = "Anna Lindqvist",
                            Phone = "070-123 45 67"
                        },
                        new
                        {
                            Id = 2,
                            Email = "erik.johansson@gmail.com",
                            Message = "Allergisk mot gluten",
                            Name = "Erik Johansson",
                            Phone = "073-234 56 78"
                        },
                        new
                        {
                            Id = 3,
                            Email = "maria.svensson@hotmail.com",
                            Name = "Maria Svensson",
                            Phone = "076-345 67 89"
                        },
                        new
                        {
                            Id = 4,
                            Email = "oskar.bergstrom@outlook.com",
                            Message = "Laktosintolerant",
                            Name = "Oskar Bergström",
                            Phone = "072-456 78 90"
                        },
                        new
                        {
                            Id = 5,
                            Email = "lina.karlsson@gmail.com",
                            Name = "Lina Karlsson",
                            Phone = "070-567 89 01"
                        },
                        new
                        {
                            Id = 6,
                            Email = "johan.nilsson@gmail.com",
                            Message = "Nötallergi, var noga!",
                            Name = "Johan Nilsson",
                            Phone = "073-678 90 12"
                        },
                        new
                        {
                            Id = 7,
                            Email = "sara.eriksson@hotmail.com",
                            Name = "Sara Eriksson",
                            Phone = "076-789 01 23"
                        },
                        new
                        {
                            Id = 8,
                            Email = "mikael.larsson@outlook.com",
                            Message = "Allergisk mot skaldjur",
                            Name = "Mikael Larsson",
                            Phone = "072-890 12 34"
                        },
                        new
                        {
                            Id = 9,
                            Email = "emma.olsson@gmail.com",
                            Name = "Emma Olsson",
                            Phone = "070-901 23 45"
                        },
                        new
                        {
                            Id = 10,
                            Email = "andreas.persson@gmail.com",
                            Name = "Andreas Persson",
                            Phone = "073-012 34 56"
                        },
                        new
                        {
                            Id = 11,
                            Email = "karin.andersson@hotmail.com",
                            Message = "Glutenintolerant och laktosintolerant",
                            Name = "Karin Andersson",
                            Phone = "076-123 45 67"
                        },
                        new
                        {
                            Id = 12,
                            Email = "peter.gustafsson@outlook.com",
                            Name = "Peter Gustafsson",
                            Phone = "072-234 56 78"
                        },
                        new
                        {
                            Id = 13,
                            Email = "sofia.magnusson@gmail.com",
                            Message = "Äggallergi",
                            Name = "Sofia Magnusson",
                            Phone = "070-345 67 89"
                        },
                        new
                        {
                            Id = 14,
                            Email = "magnus.lindstrom@gmail.com",
                            Name = "Magnus Lindström",
                            Phone = "073-456 78 90"
                        },
                        new
                        {
                            Id = 15,
                            Email = "hanna.jakobsson@hotmail.com",
                            Name = "Hanna Jakobsson",
                            Phone = "076-567 89 01"
                        },
                        new
                        {
                            Id = 16,
                            Email = "daniel.petersson@outlook.com",
                            Message = "Nötallergi",
                            Name = "Daniel Petersson",
                            Phone = "072-678 90 12"
                        },
                        new
                        {
                            Id = 17,
                            Email = "maja.henriksson@gmail.com",
                            Name = "Maja Henriksson",
                            Phone = "070-789 01 23"
                        },
                        new
                        {
                            Id = 18,
                            Email = "jonas.sandberg@gmail.com",
                            Message = "Sojaöverkänslighet",
                            Name = "Jonas Sandberg",
                            Phone = "073-890 12 34"
                        },
                        new
                        {
                            Id = 19,
                            Email = "elin.sjoberg@hotmail.com",
                            Name = "Elin Sjöberg",
                            Phone = "076-901 23 45"
                        },
                        new
                        {
                            Id = 20,
                            Email = "viktor.lundgren@outlook.com",
                            Name = "Viktor Lundgren",
                            Phone = "072-012 34 56"
                        },
                        new
                        {
                            Id = 21,
                            Email = "therese.holm@gmail.com",
                            Message = "Cöliaki, strikt glutenfri mat krävs",
                            Name = "Therese Holm",
                            Phone = "070-111 22 33"
                        },
                        new
                        {
                            Id = 22,
                            Email = "rickard.bjork@hotmail.com",
                            Name = "Rickard Björk",
                            Phone = "073-222 33 44"
                        },
                        new
                        {
                            Id = 23,
                            Email = "camilla.strand@gmail.com",
                            Message = "Laktosintolerant",
                            Name = "Camilla Strand",
                            Phone = "076-333 44 55"
                        },
                        new
                        {
                            Id = 24,
                            Email = "fredrik.holm@outlook.com",
                            Name = "Fredrik Holm",
                            Phone = "072-444 55 66"
                        },
                        new
                        {
                            Id = 25,
                            Email = "isabella.nystrom@gmail.com",
                            Name = "Isabella Nyström",
                            Phone = "070-555 66 77"
                        },
                        new
                        {
                            Id = 26,
                            Email = "tobias.engstrom@gmail.com",
                            Message = "Skaldjursallergi",
                            Name = "Tobias Engström",
                            Phone = "073-666 77 88"
                        },
                        new
                        {
                            Id = 27,
                            Email = "matilda.forsberg@hotmail.com",
                            Name = "Matilda Forsberg",
                            Phone = "076-777 88 99"
                        },
                        new
                        {
                            Id = 28,
                            Email = "simon.aberg@outlook.com",
                            Name = "Simon Åberg",
                            Phone = "072-888 99 00"
                        },
                        new
                        {
                            Id = 29,
                            Email = "johanna.blom@gmail.com",
                            Message = "Ägg- och nötallergi",
                            Name = "Johanna Blom",
                            Phone = "070-999 00 11"
                        },
                        new
                        {
                            Id = 30,
                            Email = "alexander.vang@gmail.com",
                            Name = "Alexander Vång",
                            Phone = "073-000 11 22"
                        });
                });

            modelBuilder.Entity("Stallstjarnornas.Library.Models.MailLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SentTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("MailLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookingId = 1,
                            SentDate = new DateTime(2026, 5, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            SentTo = "anna.lindqvist@gmail.com",
                            Status = "Sent"
                        },
                        new
                        {
                            Id = 2,
                            BookingId = 2,
                            SentDate = new DateTime(2026, 5, 1, 10, 5, 0, 0, DateTimeKind.Unspecified),
                            SentTo = "erik.johansson@gmail.com",
                            Status = "Sent"
                        },
                        new
                        {
                            Id = 3,
                            BookingId = 3,
                            SentDate = new DateTime(2026, 5, 2, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            SentTo = "maria.svensson@hotmail.com",
                            Status = "Sent"
                        },
                        new
                        {
                            Id = 4,
                            BookingId = 4,
                            SentDate = new DateTime(2026, 5, 2, 11, 5, 0, 0, DateTimeKind.Unspecified),
                            SentTo = "oskar.bergstrom@outlook.com",
                            Status = "Sent"
                        },
                        new
                        {
                            Id = 5,
                            BookingId = 5,
                            SentDate = new DateTime(2026, 5, 3, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            SentTo = "lina.karlsson@gmail.com",
                            Status = "Sent"
                        },
                        new
                        {
                            Id = 6,
                            BookingId = 6,
                            SentDate = new DateTime(2026, 5, 3, 12, 5, 0, 0, DateTimeKind.Unspecified),
                            SentTo = "johan.nilsson@gmail.com",
                            Status = "Failed"
                        },
                        new
                        {
                            Id = 7,
                            BookingId = 7,
                            SentDate = new DateTime(2026, 5, 4, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            SentTo = "sara.eriksson@hotmail.com",
                            Status = "Sent"
                        },
                        new
                        {
                            Id = 8,
                            BookingId = 8,
                            SentDate = new DateTime(2026, 5, 4, 13, 5, 0, 0, DateTimeKind.Unspecified),
                            SentTo = "mikael.larsson@outlook.com",
                            Status = "Sent"
                        },
                        new
                        {
                            Id = 9,
                            BookingId = 9,
                            SentDate = new DateTime(2026, 5, 5, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            SentTo = "emma.olsson@gmail.com",
                            Status = "Sent"
                        },
                        new
                        {
                            Id = 10,
                            BookingId = 10,
                            SentDate = new DateTime(2026, 5, 5, 14, 5, 0, 0, DateTimeKind.Unspecified),
                            SentTo = "andreas.persson@gmail.com",
                            Status = "Sent"
                        },
                        new
                        {
                            Id = 11,
                            BookingId = 11,
                            SentDate = new DateTime(2026, 5, 6, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            SentTo = "karin.andersson@hotmail.com",
                            Status = "Sent"
                        },
                        new
                        {
                            Id = 12,
                            BookingId = 12,
                            SentDate = new DateTime(2026, 5, 6, 15, 5, 0, 0, DateTimeKind.Unspecified),
                            SentTo = "peter.gustafsson@outlook.com",
                            Status = "Failed"
                        },
                        new
                        {
                            Id = 13,
                            BookingId = 13,
                            SentDate = new DateTime(2026, 5, 7, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            SentTo = "sofia.magnusson@gmail.com",
                            Status = "Sent"
                        },
                        new
                        {
                            Id = 14,
                            BookingId = 14,
                            SentDate = new DateTime(2026, 5, 7, 16, 5, 0, 0, DateTimeKind.Unspecified),
                            SentTo = "magnus.lindstrom@gmail.com",
                            Status = "Sent"
                        },
                        new
                        {
                            Id = 15,
                            BookingId = 15,
                            SentDate = new DateTime(2026, 5, 7, 16, 10, 0, 0, DateTimeKind.Unspecified),
                            SentTo = "hanna.jakobsson@hotmail.com",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 16,
                            BookingId = 16,
                            SentDate = new DateTime(2026, 5, 8, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            SentTo = "daniel.petersson@outlook.com",
                            Status = "Sent"
                        },
                        new
                        {
                            Id = 17,
                            BookingId = 17,
                            SentDate = new DateTime(2026, 5, 8, 10, 5, 0, 0, DateTimeKind.Unspecified),
                            SentTo = "maja.henriksson@gmail.com",
                            Status = "Sent"
                        },
                        new
                        {
                            Id = 18,
                            BookingId = 18,
                            SentDate = new DateTime(2026, 5, 8, 10, 10, 0, 0, DateTimeKind.Unspecified),
                            SentTo = "jonas.sandberg@gmail.com",
                            Status = "Failed"
                        },
                        new
                        {
                            Id = 19,
                            BookingId = 19,
                            SentDate = new DateTime(2026, 5, 9, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            SentTo = "elin.sjoberg@hotmail.com",
                            Status = "Sent"
                        },
                        new
                        {
                            Id = 20,
                            BookingId = 20,
                            SentDate = new DateTime(2026, 5, 9, 11, 5, 0, 0, DateTimeKind.Unspecified),
                            SentTo = "viktor.lundgren@outlook.com",
                            Status = "Sent"
                        });
                });

            modelBuilder.Entity("Stallstjarnornas.Library.Models.OperatingDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("Closes")
                        .HasColumnType("time");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<TimeOnly>("Opens")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("OpeningDays");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Closes = new TimeOnly(22, 0, 0),
                            Day = 1,
                            IsClosed = false,
                            Opens = new TimeOnly(17, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            Closes = new TimeOnly(22, 0, 0),
                            Day = 2,
                            IsClosed = false,
                            Opens = new TimeOnly(17, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            Closes = new TimeOnly(22, 0, 0),
                            Day = 3,
                            IsClosed = false,
                            Opens = new TimeOnly(17, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            Closes = new TimeOnly(22, 0, 0),
                            Day = 4,
                            IsClosed = false,
                            Opens = new TimeOnly(17, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            Closes = new TimeOnly(22, 0, 0),
                            Day = 5,
                            IsClosed = false,
                            Opens = new TimeOnly(17, 0, 0)
                        },
                        new
                        {
                            Id = 6,
                            Closes = new TimeOnly(22, 0, 0),
                            Day = 6,
                            IsClosed = false,
                            Opens = new TimeOnly(17, 0, 0)
                        },
                        new
                        {
                            Id = 7,
                            Closes = new TimeOnly(22, 0, 0),
                            Day = 0,
                            IsClosed = true,
                            Opens = new TimeOnly(17, 0, 0)
                        });
                });

            modelBuilder.Entity("Stallstjarnornas.Library.Models.Sitting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("MaxGuests")
                        .HasColumnType("int");

                    b.Property<int>("OperatingDayId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("OperatingDayId");

                    b.ToTable("Sittings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndTime = new TimeOnly(19, 0, 0),
                            MaxGuests = 50,
                            OperatingDayId = 1,
                            StartTime = new TimeOnly(17, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            EndTime = new TimeOnly(21, 0, 0),
                            MaxGuests = 50,
                            OperatingDayId = 1,
                            StartTime = new TimeOnly(19, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            EndTime = new TimeOnly(19, 0, 0),
                            MaxGuests = 50,
                            OperatingDayId = 2,
                            StartTime = new TimeOnly(17, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            EndTime = new TimeOnly(21, 0, 0),
                            MaxGuests = 50,
                            OperatingDayId = 2,
                            StartTime = new TimeOnly(19, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            EndTime = new TimeOnly(19, 0, 0),
                            MaxGuests = 50,
                            OperatingDayId = 3,
                            StartTime = new TimeOnly(17, 0, 0)
                        },
                        new
                        {
                            Id = 6,
                            EndTime = new TimeOnly(21, 0, 0),
                            MaxGuests = 50,
                            OperatingDayId = 3,
                            StartTime = new TimeOnly(19, 0, 0)
                        },
                        new
                        {
                            Id = 7,
                            EndTime = new TimeOnly(19, 0, 0),
                            MaxGuests = 50,
                            OperatingDayId = 4,
                            StartTime = new TimeOnly(17, 0, 0)
                        },
                        new
                        {
                            Id = 8,
                            EndTime = new TimeOnly(21, 0, 0),
                            MaxGuests = 50,
                            OperatingDayId = 4,
                            StartTime = new TimeOnly(19, 0, 0)
                        },
                        new
                        {
                            Id = 9,
                            EndTime = new TimeOnly(19, 0, 0),
                            MaxGuests = 50,
                            OperatingDayId = 5,
                            StartTime = new TimeOnly(17, 0, 0)
                        },
                        new
                        {
                            Id = 10,
                            EndTime = new TimeOnly(21, 0, 0),
                            MaxGuests = 50,
                            OperatingDayId = 5,
                            StartTime = new TimeOnly(19, 0, 0)
                        },
                        new
                        {
                            Id = 11,
                            EndTime = new TimeOnly(19, 0, 0),
                            MaxGuests = 50,
                            OperatingDayId = 6,
                            StartTime = new TimeOnly(17, 0, 0)
                        },
                        new
                        {
                            Id = 12,
                            EndTime = new TimeOnly(21, 0, 0),
                            MaxGuests = 50,
                            OperatingDayId = 6,
                            StartTime = new TimeOnly(19, 0, 0)
                        },
                        new
                        {
                            Id = 13,
                            EndTime = new TimeOnly(19, 0, 0),
                            MaxGuests = 50,
                            OperatingDayId = 7,
                            StartTime = new TimeOnly(17, 0, 0)
                        },
                        new
                        {
                            Id = 14,
                            EndTime = new TimeOnly(21, 0, 0),
                            MaxGuests = 50,
                            OperatingDayId = 7,
                            StartTime = new TimeOnly(19, 0, 0)
                        });
                });

            modelBuilder.Entity("Stallstjarnornas.Library.Models.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Seats")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Seats = 2
                        },
                        new
                        {
                            Id = 2,
                            Seats = 2
                        },
                        new
                        {
                            Id = 3,
                            Seats = 2
                        },
                        new
                        {
                            Id = 4,
                            Seats = 2
                        },
                        new
                        {
                            Id = 5,
                            Seats = 2
                        },
                        new
                        {
                            Id = 6,
                            Seats = 2
                        },
                        new
                        {
                            Id = 7,
                            Seats = 2
                        },
                        new
                        {
                            Id = 8,
                            Seats = 2
                        },
                        new
                        {
                            Id = 9,
                            Seats = 2
                        },
                        new
                        {
                            Id = 10,
                            Seats = 2
                        },
                        new
                        {
                            Id = 11,
                            Seats = 2
                        },
                        new
                        {
                            Id = 12,
                            Seats = 2
                        },
                        new
                        {
                            Id = 13,
                            Seats = 2
                        },
                        new
                        {
                            Id = 14,
                            Seats = 2
                        },
                        new
                        {
                            Id = 15,
                            Seats = 2
                        },
                        new
                        {
                            Id = 16,
                            Seats = 2
                        },
                        new
                        {
                            Id = 17,
                            Seats = 2
                        },
                        new
                        {
                            Id = 18,
                            Seats = 2
                        },
                        new
                        {
                            Id = 19,
                            Seats = 2
                        },
                        new
                        {
                            Id = 20,
                            Seats = 2
                        },
                        new
                        {
                            Id = 21,
                            Seats = 2
                        },
                        new
                        {
                            Id = 22,
                            Seats = 2
                        },
                        new
                        {
                            Id = 23,
                            Seats = 2
                        },
                        new
                        {
                            Id = 24,
                            Seats = 2
                        },
                        new
                        {
                            Id = 25,
                            Seats = 2
                        });
                });

            modelBuilder.Entity("Stallstjarnornas.Library.Models.TableAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("TableId");

                    b.ToTable("TableAssignments");
                });

            modelBuilder.Entity("Stallstjarnornas.Library.Models.Booking", b =>
                {
                    b.HasOne("Stallstjarnornas.Library.Models.Guest", "Guest")
                        .WithMany("Bookings")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stallstjarnornas.Library.Models.Sitting", "Sitting")
                        .WithMany("Bookings")
                        .HasForeignKey("SittingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");

                    b.Navigation("Sitting");
                });

            modelBuilder.Entity("Stallstjarnornas.Library.Models.MailLog", b =>
                {
                    b.HasOne("Stallstjarnornas.Library.Models.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Stallstjarnornas.Library.Models.Sitting", b =>
                {
                    b.HasOne("Stallstjarnornas.Library.Models.OperatingDay", "OperatingDays")
                        .WithMany("Sittings")
                        .HasForeignKey("OperatingDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OperatingDays");
                });

            modelBuilder.Entity("Stallstjarnornas.Library.Models.TableAssignment", b =>
                {
                    b.HasOne("Stallstjarnornas.Library.Models.Booking", "Booking")
                        .WithMany("TableAssignments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stallstjarnornas.Library.Models.Table", "Table")
                        .WithMany("TableAssignments")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("Stallstjarnornas.Library.Models.Booking", b =>
                {
                    b.Navigation("TableAssignments");
                });

            modelBuilder.Entity("Stallstjarnornas.Library.Models.Guest", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Stallstjarnornas.Library.Models.OperatingDay", b =>
                {
                    b.Navigation("Sittings");
                });

            modelBuilder.Entity("Stallstjarnornas.Library.Models.Sitting", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Stallstjarnornas.Library.Models.Table", b =>
                {
                    b.Navigation("TableAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
